### ISSUE TITLE
Can't get to work

### ISSUE THREAD

**Issue by pseudotensor** [0ssamaak0/SiriLLama#1]
* Always says something went wrong.
* readme says enter IP and flask port in shortcut area, but shortcut area says enter IP address, no place for port.  IP:5000 didn't work.
* Where is the code or explanation for the shortcut itself?
* In the app it always says "connect to chrome, allow?"  After clicking it 4-6 times it says something went wrong.

**Comment by 0ssamaak0** [comment]
Hi, I'm sorry for any inconvenience 
- regarding asking for shortcut and port there was a mistake and I fixed it (check the new shortcut link)
- the shortcut itself has no code, it's just a set of actions from Shortcuts app. anyway it's very simple and just sending API request to the predetermined link
**In the app** I don't understand which app? If you mean `app.py` you can't access it through the browser since it's POST request

**Comment by pseudotensor** [comment]
app as in, when I say Sri SriLLama, it always pops up asking to use chrome, I keep clicking to approve, but it ends up just failing int he way I said.  I explaiend this above.

**Comment by 0ssamaak0** [comment]
it's very weird. I tried it on different devices and it works fine.
Did you try running it from the Shortcut apps directly?
